### PR TITLE
0x0 is a wildcard function signature

### PR DESCRIPTION
**Pull request by ryepdx**

### CODE REVIEW

**Comment by ryepdx** [comment]
This change is necessary for the maker-core tests to pass and seems to be in line with what you were going for in `deployers/phase1.sol` of that package. Not simply merging in so that you can correct me if I'm wrong.

**Comment by nmushegian** [comment]
I thought we got ride of that line on purpose and had to add like 50 LOC because of it

**Comment by nmushegian** [comment]
Where are there still references to it?

**Comment by nmushegian** [comment]
I see what's wrong, sec

**Pull request closed without merging**
